#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef APP_ENABLE_DEBUG_BREAK
#define APP_ENABLE_DEBUG_BREAK 0
#endif

#ifndef APP_ENABLE_CONTINUOUS_MEASUREMENT
#define APP_ENABLE_CONTINUOUS_MEASUREMENT 0
#endif

#ifndef APP_ENABLE_SYNTHETIC_INPUT
#define APP_ENABLE_SYNTHETIC_INPUT 0
#endif

#ifndef APP_ENABLE_ADAPTIVE_SAMPLE_MODE
#define APP_ENABLE_ADAPTIVE_SAMPLE_MODE 1
#endif

#ifndef APP_ADAPTIVE_LOW_FREQ_THRESHOLD_HZ
#define APP_ADAPTIVE_LOW_FREQ_THRESHOLD_HZ 4000.0f
#endif

#ifndef APP_ADC_CLIP_LOW_THRESHOLD
#define APP_ADC_CLIP_LOW_THRESHOLD 8U
#endif

#ifndef APP_ADC_CLIP_HIGH_THRESHOLD
#define APP_ADC_CLIP_HIGH_THRESHOLD 4087U
#endif

#define APP_RESULT_ERROR_NONE 0x00000000U
#define APP_RESULT_ERROR_DMA_NOT_DONE 0x00000001U
#define APP_RESULT_ERROR_ADC_CLIPPED 0x00000002U
#define APP_RESULT_ERROR_FUNDAMENTAL_LOW 0x00000004U
#define APP_RESULT_ERROR_H1_BIN_OUT_OF_RANGE 0x00000008U

#endif
